apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.32
    path: deploy/chart/local-path-provisioner
    helm:
      parameters:
        - name: storageClass.defaultClass
          value: "true"
      valuesObject:
        storageClass:
          reclaimPolicy: Retain
          volumeBindingMode: WaitForFirstConsumer
        nodePathMap:
          - node: talos-controlplane
            paths:
              - /var/lib/local-path-provisioner
          - node: talos-worker
            paths:
              - /var/lib/local-path-provisioner
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /var/lib/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
