---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adguard-exporter
  namespace: adguard
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: adguard-exporter
  endpoints:
    - port: metrics
      interval: 30s
