apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-route
  namespace: adguard
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: gateway-api
  hostnames:
    - "adguard.acemagic.lab"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: adguard-home
          port: 80
