apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metrics-server
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: metrics-server
                args:
                  - --cert-dir=/tmp
                  - --secure-port=10250
                  - --kubelet-preferred-address-types=InternalDNS,Hostname,InternalIP
                  - --kubelet-use-node-status-port
                  - --kubelet-certificate-authority=/etc/ca-certificates/ca.crt
                  - --metric-resolution=15s
                volumeMounts:
                  - name: ca-cert
                    mountPath: /etc/ca-certificates
                    readOnly: true
            volumes:
              - name: ca-cert
                configMap:
                  name: extension-apiserver-authentication
                  items:
                    - key: client-ca-file
                      path: ca.crt
