apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/rumstead/homelab.git
    targetRevision: main
    path: kubernetes/manifests/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
